Basic:
  BotName: 默认名字-请更改
  MAH:
    BotQQ: 数字-机器人QQ号
    MiraiAuthKey: 字符串-MAH登录密钥
    MiraiHost: http://localhost:8080
  MiraiPath: mirai/
  Permission:
    Admin:
    - 管理员QQ
    Master: 主人QQ
    MasterName: 主人名字
  WakeText: .
TencentCloud:
  SecretId: 腾讯云SecretId
  SecretKey: 腾讯云SecretKey
AIAPI:
  Token: AIAPI_Token
Saya: {}
