Basic:
  BotName: 默认名字-请更改
  MAH:
    BotQQ: 数字-机器人QQ号
    MiraiAuthKey: 字符串-MAH登录密钥
    MiraiHost: http://localhost:8080
  MiraiPath: mirai/
  Permission:
    Admin:
    - 管理员QQ
    Master: 主人QQ
    MasterName: 主人名字
Final: true
Saya:
  jrrp:
    Disabled: false
  kedaTTS:
    Disabled: false
  sick:
    Disabled: false